### ISSUE TITLE
EPIC: Result page

### ISSUE THREAD

**Issue by Baschdl** [KDD-OpenSource/32de-UI#38]
- Display similar nodes
- 'Meta-path-contribution'-pie-chart
- Meta-path instances

**Comment by juliusrueckin** [comment]
Done. At the moment, the api endpoints provide mockup data. Therefore you need to checkout the 'add-result-page-endpoint-drafts' branch in your 32de-python repository. Graph visualizations through a Neo4jGraphRenderer will be added later, when we have implemented a way to customize the database access properties. Since our API provides cypher queries, it only requires very small changes on the result page. Please review pull request #45 :)
